project:
  type: website
  output-dir: docs

website:
  title: "Avianna"
  navbar:
    left:
      - href: about.qmd
        text: About Me
    right:
      - icon: github
        href: https://github.com/AviannaBui/portfolio_website 

format:
  html:
    theme: flatly
    css: styles.css
    toc: true



